### ISSUE TITLE
请教下工程布局

### ISSUE THREAD

**Issue by chenwuxing** [KangLin/FaceRecognizer#1]
作者您好，首先感谢您的工作，我想向您请教下如何使用SeetaFace2提供的代码做一个简单的人脸识别demo,有一个实时注册和识别的功能就好了。我现在就是心里没个大体步骤，不知如何入手，Qt也是刚学，希望您简单说下大体的步骤，谢谢您了！

**Comment by KangLin** [comment]
目前项目已支持你的需求。包含从图片注册，从图片识别，从视频注册，从视频识别。
注册可看 void CFrmRegisterImage::on_pbRegister_clicked()
识别可看 int CFrmRecognizerImage::RecognizeFace(QImage &image)
