### ISSUE TITLE
我碰到一个问题，在检测黑白图的时候无效

### ISSUE THREAD

**Issue by darkersylar** [KangLin/FaceRecognizer#2]
我是在linux下编译的，已经编译成功了，检测彩色图的时候能够准确的识别出来，但同样的图片变成黑白图的时候就检测不出来了

**Comment by KangLin** [comment]
本程序只检测视频。
你的意思是用Seeta检测图片？如果是，Seeta是可以检测灰度图片，具体的，请查看Seeta源代码。
请把出问题的代码发上来。

**Comment by KangLin** [comment]
我试了下，黑白图片可以。把你有问题的图片发给我

**Comment by darkersylar** [comment]
![3 jpg pts81](https://user-images.githubusercontent.com/22741715/69925501-86396580-14eb-11ea-9a66-d2bcb6345e97.png)
![1](https://user-images.githubusercontent.com/22741715/69925505-8cc7dd00-14eb-11ea-81f4-449b469525c9.jpg)
![1 jpg pts81](https://user-images.githubusercontent.com/22741715/69925509-8fc2cd80-14eb-11ea-8492-cb00ee786162.png)

这是我试的照片

**Comment by KangLin** [comment]
最后一张，你用什么识别的？

**Comment by darkersylar** [comment]
抱歉抱歉，我用的seetaface，发错了

**Comment by KangLin** [comment]
seeta 已经修改了
