### ISSUE TITLE
cannot build！构建出错，过不了。

### ISSUE THREAD

**Issue by hzy1992** [KangLin/FaceRecognizer#3]
![image](https://user-images.githubusercontent.com/16308278/72034550-4dea2b80-32d0-11ea-98d7-a12bcb3fc005.png)
全程按照说明构建，build过不了。master和分支都试了。

**Comment by KangLin** [comment]
暂时未测试过qt5.14.0，用低版本Qt。

**Comment by KangLin** [comment]
我试了下，在我机器上 windows10 与 ubuntu 上 qt5.14.0 能正常编译。查看你的日志，应该是你的QT没安装完全。
