### ISSUE TITLE
win10下运行,提示缺少Qt相关dll

### ISSUE THREAD

**Issue by hawdies** [KangLin/FaceRecognizer#4]
作者,你好!我下载windows安装包,安装运行后会报错缺少一些Qt的dll,我把缺少的dll文件复制到运行目录下还是启动失败.我用的是Qt5.9版本,msvc2017_64目录下的dll文件.
另外能提供一下windows下的本地编译方法吗,十分感谢!

**Comment by KangLin** [comment]
你下v0.0.4版本的
